"use client"

import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  LineChart, 
  Line, 
  AreaChart, 
  Area 
} from "recharts"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

interface AdminChartsProps {
  salesData: any[]
  performanceData: any[]
}

export default function AdminCharts({ salesData, performanceData }: AdminChartsProps) {
  return (
    <div className="grid gap-8 lg:grid-cols-2">
      {/* Overall Sales Graph */}
      <Card className="border-none bg-white shadow-sm ring-1 ring-gray-100 rounded-3xl overflow-hidden">
        <CardHeader className="p-8 pb-4">
          <CardTitle className="text-lg font-black tracking-tight text-black">Overall Sales Trend</CardTitle>
          <p className="text-xs font-medium text-gray-400">Total revenue generated over time.</p>
        </CardHeader>
        <CardContent className="p-8 pt-0">
          <div className="h-[300px] w-full mt-4">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={salesData}>
                <defs>
                  <linearGradient id="colorSales" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#000" stopOpacity={0.1}/>
                    <stop offset="95%" stopColor="#000" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                <XAxis 
                  dataKey="name" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 10, fontWeight: 700, fill: '#9ca3af' }}
                  dy={10}
                />
                <YAxis 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 10, fontWeight: 700, fill: '#9ca3af' }}
                  tickFormatter={(value) => `₹${(value / 1000)}k`}
                />
                <Tooltip 
                  contentStyle={{ 
                    borderRadius: '16px', 
                    border: 'none', 
                    boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)',
                    fontSize: '12px',
                    fontWeight: 700
                  }}
                  formatter={(value: any) => [`₹${value.toLocaleString()}`, "Sales"]}
                />
                <Area 
                  type="monotone" 
                  dataKey="total" 
                  stroke="#000" 
                  strokeWidth={3} 
                  fillOpacity={1} 
                  fill="url(#colorSales)" 
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>

      {/* Individual Salesmen Performance */}
      <Card className="border-none bg-white shadow-sm ring-1 ring-gray-100 rounded-3xl overflow-hidden">
        <CardHeader className="p-8 pb-4">
          <CardTitle className="text-lg font-black tracking-tight text-black">Team Performance</CardTitle>
          <p className="text-xs font-medium text-gray-400">Total revenue generated by each salesperson.</p>
        </CardHeader>
        <CardContent className="p-8 pt-0">
          <div className="h-[300px] w-full mt-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={performanceData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                <XAxis 
                  dataKey="name" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 10, fontWeight: 700, fill: '#9ca3af' }}
                  dy={10}
                />
                <YAxis 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fontSize: 10, fontWeight: 700, fill: '#9ca3af' }}
                  tickFormatter={(value) => `₹${(value / 1000)}k`}
                />
                <Tooltip 
                  cursor={{ fill: '#f9fafb' }}
                  contentStyle={{ 
                    borderRadius: '16px', 
                    border: 'none', 
                    boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)',
                    fontSize: '12px',
                    fontWeight: 700
                  }}
                  formatter={(value: any) => [`₹${value.toLocaleString()}`, "Total Revenue"]}
                />
                <Bar 
                  dataKey="total" 
                  fill="#000" 
                  radius={[8, 8, 0, 0]} 
                  barSize={40}
                />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
